[features]
seeds = false
skip-lint = false

[programs.devnet]
gpu_dex = "BRpDctiHbH3jC19VpcSBbKgKUJEnAqiuGWNwQEYv8Nzf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
initialize_gpu_mint = "anchor run -- provider.cluster devnet"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"