[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
gpu_dex = "6KoWc2Ld2aJEze3PbBidw7r81wAKPRVUykgvpVsw9a8H"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
initialize_gpu_mint = "ts-node scripts/initialize_gpu_mint.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
